# Generated by Django 2.2 on 2020-08-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilizer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='operationmanager',
            name='email',
        ),
    ]
