# Generated by Django 2.2 on 2020-08-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200816_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='filename',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
