# Generated by Django 2.2 on 2020-08-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200816_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilizer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
