# Generated by Django 2.2 on 2020-08-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mobilizer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
