# Generated by Django 2.2 on 2020-08-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200816_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='mobiliser_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Mobilizer'),
            preserve_default=False,
        ),
    ]
