# Generated by Django 2.2 on 2020-08-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_students_mobiliser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
